apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: canary-demo

data:
  index.html: |
    <html>
      <head>
        <title>Argo Canary Demo</title>
      </head>

      <body>
        <h1>ARGO CANARY DEPLOYMENT</h1>

        <h2>Version: BLUE</h2>

        <h3>Hello from Version 1</h3>
      </body>
    </html>